../programm/programm: ../code/main.c asciiCode.o einMalEins.o intToBin.o
	gcc -o ../programm/programm ../code/main.c asciiCode.o einMalEins.o intToBin.o

asciiCode.o: ../code/asciiCode.c 
	gcc -c ../code/asciiCode.c

einMalEins.o: ../code/einMalEins.c 
	gcc -c ../code/einMalEins.c 

intToBin.o: ../code/intToBin.c 
	gcc -c ../code/intToBin.c 