../programm/programm: ../code/main.c toUpperCase.o arrayToUpperCase.o queue.o
	gcc -o ../programm/programm ../code/main.c toUpperCase.o arrayToUpperCase.o queue.o

toUpperCase.o: ../code/toUpperCase.c
	gcc -c ../code/toUpperCase.c 

arrayToUpperCase.o: ../code/arrayToUpperCase.c
	gcc -c ../code/arrayToUpperCase.c

queue.o: ../code/queue.c 
	gcc -c ../code/queue.c 